// Mirrors the serde types in crates/downasaur-core/src/model.rs (camelCase).

export type Platform = "youtube" | "tiktok" | "instagram" | "twitch" | "twitter" | "facebook" | "generic";
export type VideoCodec = "av1" | "vp9" | "hevc" | "h264" | "unknown";
export type AudioCodec = "opus" | "aac" | "mp3" | "flac" | "unknown";
export type StreamKind = "muxed" | "videoOnly" | "audioOnly";
export type ContentKind = "video" | "short" | "story" | "liveStream" | "vod";
export type Resolution = "360p" | "480p" | "720p" | "1080p" | "1440p" | "2160p" | "4320p";
export type Container = "mp4" | "mkv";
export type AudioOutput = "mp3" | "m4a" | "opus" | "flac";

export type Transport =
  | { type: "http"; contentLength: number | null }
  | { type: "hls"; live: boolean }
  | { type: "dash" };

export interface StreamFormat {
  id: string;
  url: string;
  kind: StreamKind;
  transport: Transport;
  container: string;
  width: number | null;
  height: number | null;
  fps: number | null;
  videoCodec: VideoCodec | null;
  audioCodec: AudioCodec | null;
  bitrate: number | null;
  hdr: boolean;
}

export interface SubtitleTrack {
  language: string;
  label: string;
  url: string;
  format: string;
  autoGenerated: boolean;
}

export interface MediaInfo {
  platform: Platform;
  id: string;
  sourceUrl: string;
  title: string;
  author: string | null;
  thumbnail: string | null;
  durationSecs: number | null;
  publishedAt: string | null;
  contentKind: ContentKind;
  formats: StreamFormat[];
  subtitles: SubtitleTrack[];
}

export type Extraction =
  | ({ type: "media" } & MediaInfo)
  | { type: "collection"; platform: Platform; title: string; entries: string[]; continuation: string | null };

export type DownloadProfile =
  | { type: "video"; maxResolution: Resolution; container: Container }
  | { type: "audioOnly"; format: AudioOutput }
  | { type: "noWatermark" };

export type TaskState =
  | "queued"
  | "scheduled"
  | "fetching"
  | "downloading"
  | "paused"
  | "muxing"
  | "organizing"
  | "completed"
  | "failed"
  | "cancelled";

export interface DownloadTask {
  id: string;
  sourceUrl: string;
  platform: Platform;
  title: string;
  author: string | null;
  profile: DownloadProfile;
  state: TaskState;
  bytesTotal: number | null;
  bytesDone: number;
  destination: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export type ProgressEvent =
  | { kind: "download"; taskId: string; bytesDone: number; bytesTotal: number | null; speedBps: number; etaSecs: number | null }
  | { kind: "muxing"; taskId: string; percent: number; label: string }
  | { kind: "state"; taskId: string; state: TaskState; message: string | null }
  | { kind: "organized"; taskId: string; destination: string };

export interface MediaSeparation {
  enabled: boolean;
  audioDir: string;
  eightKDir: string;
  shortsDir: string;
}

export interface OrganizerRules {
  enabled: boolean;
  targetDir: string;
  pattern: string;
  separation: MediaSeparation;
  cleanNames: boolean;
}

export interface ScheduleWindow {
  start: string; // "HH:MM:SS"
  end: string;
  days: string[];
}

export interface SchedulerConfig {
  enabled: boolean;
  windows: ScheduleWindow[];
  bandwidthLimit: number | null;
  pauseOnMetered: boolean;
}

export interface SniffResult {
  platform: Platform;
  displayName: string;
}

/** Serialized `CoreError`. */
export interface CoreError {
  code: string;
  message: string;
}
